---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  tag:workshop: ansible-lab
  instance-state-name:
    - pending
    - running
keyed_groups:
  - key: ec2_tags.Name
    prefix: tag
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address
